# Generated by Django 4.1 on 2022-09-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('videoFile', models.FileField(upload_to='D:\\M Tech DSE Bits\\Semester 3\\Information Retrieval\\Assignments\\Assignment 2\\Data\\\\')),
            ],
        ),
    ]
