# Generated by Django 4.1 on 2022-09-04 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video_search_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='pubDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='video',
            name='videoFile',
            field=models.FileField(upload_to='video'),
        ),
    ]
