# Generated by Django 4.1 on 2022-09-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_search_engine', '0002_video_pubdate_alter_video_name_alter_video_videofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='author',
            field=models.CharField(default='Deeplearning.ai', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='image'),
            preserve_default=False,
        ),
    ]
